### ISSUE TITLE
Support for different versions of kubectl or helm

### ISSUE THREAD

**Issue by endzyme** [reactiveops/rok8s-scripts#234]
Idea: Could we support multiple versions of helm and kubectl (or any commonly versioned tools) within the same major version of rok8s-scripts - so it's not all or nothing on upgrades. 

Basic thought - entrypoint on container would read `HELM_VERSION` and `KUBECTL_VERSION` and if not set it would follow whatever the latest supported. But we could have older versions available (not all but some supported) so people can pin their underlying dependencies. 

EX: We upgraded helm to new version due to CVE - but we could support pinning to old one and just warn in pipeline that they should upgrade if they've pinned.

**Comment by ejether** [comment]
Since the tools are installed at image build time, I think this would require an install step built in if the installed version != `foo_VERSION` (which isn't a big deal). I think messaging might be important in case someone tries to use, for example, a really new helm version with an outdated image tag or vice versa... so "Officially Supported" version vs "Use this setting at great peril" might be an important distinction in the docs.

**Comment by endzyme** [comment]
Good point - I was envisioning shipping the build image with 2-3 versions of each tool, and entrypoint would handle aliasing versions to the right version - 

e.g. Entrypoint => If no thing set then alias helm=helm2.12.2 => if it is set and file exists then alias helm=helm2.10.0 => if file no exists, try to install it (optional)

RE: Messaging - very good call out - this could be built into the aliasing function at init time for "supported versions".

**Comment by endzyme** [comment]
Closing due to minimal value.
