### ISSUE TITLE
Give more details on deploy timeout.

### ISSUE THREAD

**Issue by robwar** [reactiveops/rok8s-scripts#44]
From PA suggestion: Perhaps we could provide a tail of `logs` or `describe` on pods that aren't coming up as quickly as possible and cause timeouts.

**Comment by philipcristiano** [comment]
This would be nice to always call describe on failed deploys. We have the deployment name easily available and could enumerate pods and describe each one so it would be available in the CI logs. #23 would likely make this more difficult as we need to extract the deployment name from the file instead of assuming it matches the filename, but certainly doable.
